name: Testing My published javascript action
on:
  push:
    branches:
      - "develop"
jobs:
  test-published-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ManojCSE17/open-issue@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Some Issue Title
          body: Some Issue Body
          assignees: |
            ManojCSE17
      - uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Some Issue Title
          body: Some Issue Body
          assignees: |
            manojitdev