name: Greet Action Impl

on:
  push:
    branches:
      - "develop"

jobs:
  greet-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/greet
        id: greet-action-first-step
        with:
          whom-to-greet: "Manoj"
      - name: second step
        run: |
          echo "Time : ${{ steps.greet-action-first-step.outputs.time-of-greet }}"
          echo "evar: ${evar}"
      - uses: ./.github/actions/issue
        id: issue-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated issue for commit: ${{ github.sha }}"
          assignees: |
            ManojCSE17
            manojitdev
        run: |
          echo ${{ steps.issue-action.outputs.issue }}